### ISSUE TITLE
fix twitter og:image

### ISSUE THREAD

**Issue by kaminskypavel** [kaminskypavel/iron-swords-missing#12]
it looks like this 
<img width="418" alt="image" src="https://github.com/kaminskypavel/iron-swords-missing/assets/4253088/aae3dda2-db89-4df0-96e5-09588e6c49cc">

**Comment by jossef** [comment]
on it

**Comment by kaminskypavel** [comment]
can this be closed? @jossef @vithano ?

**Comment by vithano** [comment]
Yes

**Comment by kaminskypavel** [comment]
closing. looks good [here](https://www.opengraph.xyz/url/https%3A%2F%2Fwww.ironswords.org.il) 

lets wait it out with twitter
