### ISSUE TITLE
Report "Gaza Now" Paypal account button 

### ISSUE THREAD

**Issue by Eliran-dev** [kaminskypavel/iron-swords-missing#24]
Add a button that can report "Gaza now" PayPal account - must be changed manually.
Can open paypal report tab or email directly to paypal, with copied text.
https://t.me/gazaalannet

**Comment by kaminskypavel** [comment]
we should concentrate on helping the missing. there are accounts that help report stuff like this, we can refer to them. 
but lets stay focused on keep helping the missing
