### ISSUE TITLE
Potentially SQL injection

### ISSUE THREAD

**Issue by idandagan1** [kaminskypavel/iron-swords-missing#25]
Following this [line](https://github.com/kaminskypavel/iron-swords-missing/blob/master/src/app/api/supabase/route.tsx#L19) 

```js
      .or(`first_name.ilike.%${name}%,last_name.ilike.%${name}%`);
```

the query formation using template literals could expose the application to SQL injection if the name variable comes from user input. Consider using parameterized queries or another method to sanitize the inputs.

**Comment by idandagan1** [comment]
ah @vithano the queries are in fetch-db-data.ts? Do you want me to make the changes there? because it has the same vulnerability.

**Comment by kaminskypavel** [comment]
@vithano @idandagan1 has this been merged at some point?

**Comment by idandagan1** [comment]
No

**Comment by vithano** [comment]
Go ahead
