### ISSUE TITLE
Integrate with "needarim" organization

### ISSUE THREAD

**Issue by idandagan1** [kaminskypavel/iron-swords-missing#35]
They contact us and they want to merge their list into our system.

Need to write a script to get their list, and insert into our DB.

https://needarim.co.il/

**Comment by idandagan1** [comment]
I'm on it

**Comment by tounano** [comment]
@idandagan1 I wrote the script, sent pavel the CSV.

I didn't upload the script here, as I think such things are better to be in a private repo.

**Comment by kaminskypavel** [comment]
thanks guys, this is merged. closing!
